name: WiNSys
url: http://WiNSys.edu.in

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: "Faculty"
  - key: phd
    name: "Current PhD Students"
  - key: alum
    name: "Alumni"

# Number of news stories on the front page.
front_page_news: 5

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: "{{ site.baseurl }}/"
  - title: People
    link: "{{ site.baseurl }}/people.html"
  - title: Research
    link: "{{ site.baseurl }}/research.html"
  - title: Publications
    link: "{{ site.baseurl }}/publications.html"
  - title: Talks
    link: "{{ site.baseurl }}/talks.html"
  - title: Awards
    link: "{{ site.baseurl }}/awards.html"
